# Generated by Django 5.0.7 on 2024-07-28 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(default=0, max_length=10)),
                ('name', models.CharField(default=None, max_length=64)),
                ('item', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64)),
                ('comment', models.TextField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('photo', models.URLField(default='https://t4.ftcdn.net/jpg/04/70/29/97/360_F_470299797_UD0eoVMMSUbHCcNJCdv2t8B2g1GVqYgs.jpg')),
                ('category', models.CharField(blank=True, max_length=64)),
                ('starting_bid', models.FloatField(default=0, max_length=64)),
                ('number_of_bids', models.FloatField(default=0, max_length=8)),
                ('time_of_listing', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
