# Generated by Django 5.0.7 on 2024-08-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_bids_comments_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key='listing', serialize=False, to='auctions.listings'),
        ),
    ]
