# Generated by Django 5.0.6 on 2024-07-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='listings',
            name='starting_bid',
            field=models.FloatField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='listings',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
