# Generated by Django 5.0.7 on 2024-07-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_time_of_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='time_of_listing',
            field=models.TimeField(default=None),
        ),
    ]
