# Generated by Django 5.0.7 on 2024-08-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_item_alter_listings_number_of_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='listing_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
