# Generated by Django 5.0.7 on 2024-07-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_time_of_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='bid',
            new_name='bid_amount',
        ),
    ]
