# Generated by Django 5.0.7 on 2024-07-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bid_bids_bid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('listing', models.CharField(blank=True, max_length=64, primary_key='title', serialize=False)),
            ],
        ),
    ]
