# Generated by Django 5.0.7 on 2024-07-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='addRemove',
            field=models.BooleanField(default=False),
        ),
    ]
