# Generated by Django 5.0.7 on 2024-08-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listings_id_alter_listings_listing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='item',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='auction',
            new_name='listing',
        ),
    ]
