# Generated by Django 5.0.6 on 2024-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist_addremove'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.CharField(blank=True, default='', max_length=64, primary_key='title', serialize=False),
        ),
    ]
