# Generated by Django 5.0.6 on 2024-08-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bids_number_of_bids_alter_watchlist_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='number_of_bids',
        ),
        migrations.AlterField(
            model_name='listings',
            name='number_of_bids',
            field=models.FloatField(default=0),
        ),
    ]
