# Generated by Django 5.0.6 on 2024-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bids_number_of_bids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
    ]
