# Generated by Django 5.0.6 on 2024-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listings_number_of_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='number_of_bids',
            field=models.IntegerField(default=None),
        ),
    ]
